"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'y4i%5mt@k*mj6=-m!9%er*c$h7p3n%j1$s+mf&dl-u+b6pm-5d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    #--------------- [edit] ---------------#
    'pybo.apps.PyboConfig',
    'common.apps.CommonConfig',
    #--------------- [edit] ---------------#
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #--------------------------- [edit] ---------------------------#
    #여기서 csrf토큰을 제거할 수 도있다. 되도록 하지말자
    'django.middleware.csrf.CsrfViewMiddleware',
    #--------------------------- [edit] ---------------------------#
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #--------------------------- [edit] ---------------------------#
        #html파일들 경로를 templates로 통합하여 편리하게 이용가능하다
        'DIRS': [BASE_DIR / 'templates'],
        #--------------------------- [edit] ---------------------------#
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

#-------------[edit]-------------#
LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'
#-------------[edit]-------------#

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
#----------------------------------------------[EDIT]----------------------------------------------#
"""
스타일 시트의 경우 settings.py에 연결 링크를 걸어준다.
"""
STATICFILES_DIRS = [
    BASE_DIR / 'static'
]
#----------------------------------------------[EDIT]----------------------------------------------#

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
#----------------------------------------------[EDIT]----------------------------------------------#
